# Generated by Django 3.1 on 2021-10-01 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='listing',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
