# Generated by Django 3.1 on 2021-10-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20211001_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(related_name='allListing', to='auctions.Category'),
        ),
    ]
