# Generated by Django 3.1 on 2021-10-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_newbids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='newBids',
        ),
    ]
